import Header from "@/components/layout/Header";
import "./globals.css";
import { Sora } from "next/font/google";
import Providers from "@/components/Provider";
import Wrapper from "@/components/Wrapper";
import Footer from "@/components/layout/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Wrapper>
            <Providers>
              <Header />
              <main className="px-20">
                {children}
                <Footer />
              </main>
            </Providers>
          </Wrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
